### ISSUE TITLE
Improve Inference Endpoints Engine

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/distilabel#39]
We need to add do_sample, top_k, etc.

```[tasklist]
### Tasks
- [x] Read `token` from `HUGGING_FACE_HUB_TOKEN`
- [x] Extend args and align `_generate` methods overall
- [x] Move out of huggingface.py
```
