### ISSUE TITLE
[FEATURE] Saving/Loading of Distiset with S3 bucket (or locally)

### ISSUE THREAD

**Issue by rasdani** [argilla-io/distilabel#665]
**Is your feature request related to a problem? Please describe.**
In some cases one does not want to save datasets to HF hub or locally. S3 buckets are a common object storage offered by most cloud providers and can be used with `Dataset.save_to_disk(s3_path, storage_options=storage_options`).

**Describe the solution you'd like**
Implement a `Distiset.save_to_disk()` method that wraps `Dataset.save_to_disk()`, such that the complete `Distiset` (including config and model card) can be saved to an S3 bucket.
Saving locally should come for free, if implemented correctly :)

**Describe alternatives you've considered**
Implementing loading and saving as `Steps` or basic Python functions. (This is what we have currently internally at ellamind).
Currently there is also `Distiset.create_distiset()`, if this can be reused, I will do so.

**Additional context**
You can assign me to the task. I will try converting our custom S3 saving/loading stuff.

```[tasklist]
### Tasks
- [ ] Look into if/how saving locally is already implemented
- [ ] Wrap `save_to_disk()` and make it work locally
- [ ] Make it work with S3
```

**Comment by gabrielmbmb** [comment]
Hi @rasdani, we can work on our side on this one but if you already have some stuff we're happy to accept your contribution!

**Comment by plaguss** [comment]
Hi @rasdani will assign this one myself, will let you know once we have a draft for it 🙂

**Comment by rasdani** [comment]
This is what we currently have internally. A loading step and a saving function:
```python
class LoadS3HFDataset(LoadHubDataset):
    num_samples: int = -1

    def load(self):
        if any(key not in os.environ for key in ["S3_ACCESS_KEY", "S3_SECRET_KEY"]):
            raise ValueError("Missing S3 credentials. Set S3_ACCESS_KEY and S3_SECRET_KEY.")
        storage_options = {
            "key": os.environ["S3_ACCESS_KEY"],
            "secret": os.environ["S3_SECRET_KEY"],
            "client_kwargs": {
                "endpoint_url": os.environ.get("S3_ENDPOINT_URL", "https://s3.gra.io.cloud.ovh.net/"),
                "region_name": os.environ.get("S3_REGION", "gra"),
            },
        }
        # breakpoint()
        self._dataset = datasets.load_from_disk(self.repo_id, storage_options=storage_options)
        if self.num_samples > 0:
            self._dataset = self._dataset.select(min(range(self.num_samples), len(self._dataset)))
        if "date" in self._dataset.column_names:
            self._dataset = self._dataset.map(lambda x: {"date": x["date"].strftime("%d.%m.%Y")})
        self._logger = logging.getLogger(f"distilabel.step.{self.name}")

    def _get_dataset_num_examples(self):
        return len(self._dataset)

    def _get_dataset_columns(self):
        return list(self._dataset.column_names)

    @property
    def outputs(self) -> List[str]:
        """The columns that will be generated by this step, based on the datasets loaded
        from the Hugging Face Hub.

        Returns:
            The columns that will be generated by this step.
        """
        if not isinstance(self._dataset, datasets.Dataset):
            self.load()
            print("loaded")
        return self._get_dataset_columns()
```

```python
# TODO: save full Distiset with dataset card and config and rewrite as step
def save_distiset_to_s3(distiset: Distiset, s3_path: str) -> None:
    confirmed = input(f"Are you sure you want to save the distiset to {s3_path}? (y/n): ")
    if confirmed.lower() != "y":
        return
    # if not isinstance(distiset, Dataset):
    dataset = list(distiset.values())[0]
    # else:
    # dataset = distiset
    # if "train" not in dataset:
    #     dataset["train"] = dataset
    storage_options = {
        "key": os.environ["S3_ACCESS_KEY"],
        "secret": os.environ["S3_SECRET_KEY"],
        "client_kwargs": {
            "endpoint_url": os.environ.get("S3_ENDPOINT_URL", "https://s3.gra.io.cloud.ovh.net/"),
            "region_name": os.environ.get("S3_REGION", "gra"),
        },
    }
    dataset["train"].save_to_disk(
        s3_path,
        storage_options=storage_options,
    )
    # dataset.save_to_disk(
    #     s3_path,
    #     storage_options=storage_options,
    # )
    ```

If you implement the local saving, we can make sure everything works with S3.

**Comment by rasdani** [comment]
> Hi @rasdani will assign this one myself, will let you know once we have a draft for it 🙂

Nice! Looking forward to it :)
