### ISSUE TITLE
[DOCS] Add examples for the components gallery

### ISSUE THREAD

**Issue by plaguss** [argilla-io/distilabel#697]
## Which page or section is this issue related to?

 I truly love the components gallery but I think it might benefit from some code snippets that I can use to copy-paste a pipeline together, which could just be based on API references. (edited) 

"The logic for rendering the example is there, but not the examples! :laughing:"

## What are you documenting, or what change are you making in the documentation?

Add examples.
```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/distilabel/issues/709
- [ ] https://github.com/argilla-io/distilabel/issues/710
- [ ] https://github.com/argilla-io/distilabel/issues/711
```
