### ISSUE TITLE
Basic docs

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/distilabel#81]
```[tasklist]
### Tasks
- [ ] Introduce basic structure with mkdocs material
- [ ] Add API reference of main classes and contents
- [ ] Publication of docs
```
