### ISSUE TITLE
[FEATURE] Add `set_structured_output` method to `LLM` so `Task`s can configure it

### ISSUE THREAD

**Issue by gabrielmbmb** [argilla-io/distilabel#832]
**Is your feature request related to a problem? Please describe.**
There are some `Task`s that are intended to be used with structured output (e.g. a json schema defining the output of the LLM). Right now, the user has to take care of that and be aware that the `Task` works better with structured output and specifying the `structured_output` argument manually when instantiating the `LLM` class to be used by the `Task`.

**Describe the solution you'd like**
`Task`s can define a preferred `structured_output` and they can call a `set_structured_output` method of the `LLM` to automatically set this preferred `structured_output`.
```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/distilabel/issues/867
- [ ] https://github.com/argilla-io/distilabel/issues/869
- [ ] https://github.com/argilla-io/distilabel/issues/872
- [ ] https://github.com/argilla-io/distilabel/issues/874
```

**Comment by plaguss** [comment]
This means for example defining a predefined format for `Ultrafeedback` so we automatically use structured generation if nothing else is informed?
